# Добавьте правила для автоматического labeling
kubernetes:
  - kubernetes-intro/**/*

homework:
  - kubernetes-intro/**/*

namespace:
  - kubernetes-intro/namespace.yaml

pod:
  - kubernetes-intro/pod.yaml
