{{- if .Values.serviceAccounts.monitoring.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}-monitoring
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
{{- end }}
