{{- if .Values.volumes.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.pvc.size }}
  {{- if .Values.volumes.pvc.storageClass }}
  storageClassName: {{ .Values.volumes.pvc.storageClass }}
  {{- end }}
{{- end }}
